---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idmocp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: idmocp
  template:
    metadata:
      labels:
        name: idmocp
    spec:
      serviceAccountName: idmocp
      containers:
        - name: idmocp
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
            - idmocp
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "idmocp"
